In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns


In [15]:
from sklearn.datasets import load_iris
import pandas as pd

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Convert to DataFrame for easier viewing
df = pd.DataFrame(data=X, columns=iris.feature_names)
df['target'] = y

print(df.head())


   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0  


In [16]:
from sklearn.preprocessing import StandardScaler

# Standardize the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)



In [17]:
from sklearn.model_selection import train_test_split

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)


## One vs Rest Approach

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Train the logistic regression model using OvR
model_ovr = LogisticRegression(multi_class='ovr', max_iter=200)
model_ovr.fit(X_train, y_train)

# Predict on the test set
y_pred_ovr = model_ovr.predict(X_test)

# Calculate accuracy
accuracy_ovr = accuracy_score(y_test, y_pred_ovr)
print(f'OvR Accuracy: {accuracy_ovr}')

# Generate confusion matrix
conf_matrix_ovr = confusion_matrix(y_test, y_pred_ovr)
print(f'OvR Confusion Matrix:\n{conf_matrix_ovr}')

# Classification report
class_report_ovr = classification_report(y_test, y_pred_ovr)
print(f'OvR Classification Report:\n{class_report_ovr}')


OvR Accuracy: 0.9666666666666667
OvR Confusion Matrix:
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
OvR Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30



In [20]:
# Train the logistic regression model using Softmax Regression
model_softmax = LogisticRegression(multi_class='multinomial', solver='lbfgs', max_iter=200)
model_softmax.fit(X_train, y_train)

# Predict on the test set
y_pred_softmax = model_softmax.predict(X_test)

# Calculate accuracy
accuracy_softmax = accuracy_score(y_test, y_pred_softmax)
print(f'Softmax Accuracy: {accuracy_softmax}')

# Generate confusion matrix
conf_matrix_softmax = confusion_matrix(y_test, y_pred_softmax)
print(f'Softmax Confusion Matrix:\n{conf_matrix_softmax}')

# Classification report
class_report_softmax = classification_report(y_test, y_pred_softmax)
print(f'Softmax Classification Report:\n{class_report_softmax}')


Softmax Accuracy: 1.0
Softmax Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Softmax Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

